In [1]:
!python -m pip install tweepy

Requirement already satisfied: tweepy in c:\users\shayna\appdata\local\programs\python\python310\lib\site-packages (4.8.0)
Requirement already satisfied: requests<3,>=2.27.0 in c:\users\shayna\appdata\local\programs\python\python310\lib\site-packages (from tweepy) (2.27.1)
Requirement already satisfied: oauthlib<4,>=3.2.0 in c:\users\shayna\appdata\local\programs\python\python310\lib\site-packages (from tweepy) (3.2.0)
Requirement already satisfied: requests-oauthlib<2,>=1.2.0 in c:\users\shayna\appdata\local\programs\python\python310\lib\site-packages (from tweepy) (1.3.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\shayna\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.27.0->tweepy) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\shayna\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.27.0->tweepy) (1.26.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\shayna\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.27.0->tweepy) (2.0.10)
Requirement already satisfied: idna<4,>=2.5 in c:\users\shayna\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.27.0->tweepy) (3.3)

WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available.
You should consider upgrading via the 'C:\Users\Shayna\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

In [2]:
import tweepy
from config import bearer_token

client = tweepy.Client(bearer_token)

In [3]:
num_loops = 100
num_results_per_loop = 100
next_token = None

ids = []
tweet_texts = []
public_metrics = []
created_times = []
sources = []
languages = []

for i in range(num_loops):
    print(f"Request {i}    ===========")
    
    response = client.search_recent_tweets("funny", 
                                           max_results=num_results_per_loop, 
                                           next_token=next_token,
                                           tweet_fields=['id', 'text', 'author_id', 'created_at', 'public_metrics','source', 'lang'])
    # The method returns a Response object, a named tuple with data, includes,
    # errors, and meta fields
    print(response.meta)

    # In this case, the data field of the Response returned is a list of Tweet
    # objects
    tweets = response.data
    
    # Each Tweet object has default ID and text fields
    for tweet in tweets:
        ids.append(tweet.id)
        tweet_texts.append(tweet.text)
        created_times.append(tweet.created_at)
        sources.append(tweet.source)
        public_metrics.append(tweet.public_metrics)
        languages.append(tweet.lang)
        
        
        
    next_token = response.meta['next_token']
    
    print()

Request 0    ===========
{'newest_id': '1518731013777670146', 'oldest_id': '1518730946962509825', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe63aw7tygtqottg0jfew37at9'}

Request 1    ===========
{'newest_id': '1518730946761183232', 'oldest_id': '1518730866796675078', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe63aw7mc3mxfmhr7x5rdznssd'}

Request 2    ===========
{'newest_id': '1518730866742149120', 'oldest_id': '1518730780184395777', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe63aw7eppj7wsf5lcow4k5q4d'}

Request 3    ===========
{'newest_id': '1518730779584573444', 'oldest_id': '1518730697388613632', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe63aw772aiuruv884lti0lx19'}

Request 4    ===========
{'newest_id': '1518730697384419328', 'oldest_id': '1518730618175213570', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe63aw76tnky618xt120aaffy5'}

Request 5    ===========
{'newest_id': '1518730617529143297', 'oldest_id': '1518730543906533376', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe63aw6z8cix8vppvlmk10t8xp'}

Request 6    ===========
{'newest_id': '1518730543021576193', 'oldest_id': '1518730445818630151', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe63aw6rjtv8hxxc420feeu6bh'}

Request 7    ===========
{'newest_id': '1518730445101359104', 'oldest_id': '1518730373924016128', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe63aw6jyj9gt3f4l9oeh41bi5'}

Request 8    ===========
{'newest_id': '1518730373550596096', 'oldest_id': '1518730300813049856', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe63aw6jqylmibs82zotq3jgql'}

Request 9    ===========
{'newest_id': '1518730298493652994', 'oldest_id': '1518730227630977026', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe63aw6c4mh3ajtwiceglpu931'}

Request 10    ===========
{'newest_id': '1518730227509309441', 'oldest_id': '1518730137075863553', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe63aw64h6e9z1j62qntkz156l'}

Request 11    ===========
{'newest_id': '1518730136614424577', 'oldest_id': '1518730049721356288', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe63aw5wtqmoclnmvieqwwpy0t'}

Request 12    ===========
{'newest_id': '1518730049536602112', 'oldest_id': '1518729964539068416', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630hg28c07z8c53xm6spug71'}

Request 13    ===========
{'newest_id': '1518729963381600256', 'oldest_id': '1518729897413427200', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630hfun25r22puneh3ha27i5'}

Request 14    ===========
{'newest_id': '1518729896779911168', 'oldest_id': '1518729816106692608', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630hfueewvyf1amm2nx7yr25'}

Request 15    ===========
{'newest_id': '1518729814986821632', 'oldest_id': '1518729734573764611', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630hfms1f9lld3f8vxrhlmd9'}

Request 16    ===========
{'newest_id': '1518729734489792512', 'oldest_id': '1518729653283917826', 'result_count': 99, 'next_token': 'b26v89c19zqg8o3fpytoe630hff5o2ypesz1ssixus7el'}

Request 17    ===========
{'newest_id': '1518729651530706945', 'oldest_id': '1518729572895838210', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630hf7jaquqduvp0j0cox8cd'}

Request 18    ===========
{'newest_id': '1518729572589711361', 'oldest_id': '1518729501488070656', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630hf7bqdvupyeormmaaey65'}

Request 19    ===========
{'newest_id': '1518729501152272390', 'oldest_id': '1518729420302954497', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630hezpd1mgxibm388vzcfb1'}

Request 20    ===========
{'newest_id': '1518729417912057856', 'oldest_id': '1518729351558217730', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630hes42wa5fnd97fk7o52m5'}

Request 21    ===========
{'newest_id': '1518729350253842434', 'oldest_id': '1518729282431819776', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630hekisqvi4haomq7cdbtdp'}

Request 22    ===========
{'newest_id': '1518729282071183362', 'oldest_id': '1518729203994222592', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630heka5t4aujmehpcj6r1j1'}

Request 23    ===========
{'newest_id': '1518729202329079809', 'oldest_id': '1518729120431185925', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630hecns5u4dwwvd1h27pkzh'}

Request 24    ===========
{'newest_id': '1518729119692775424', 'oldest_id': '1518729044874956800', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630he51fl0xp99yq2gyhqzr1'}

Request 25    ===========
{'newest_id': '1518729044476497920', 'oldest_id': '1518728964264452096', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630fxfthxs81sku3k8w3aagt'}

Request 26    ===========
{'newest_id': '1518728964205953027', 'oldest_id': '1518728891631874048', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630fx8876lyqtp8d49n8tchp'}

Request 27    ===========
{'newest_id': '1518728891451330560', 'oldest_id': '1518728818588106753', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630fx7zl5jbpxtft9cik9ym5'}

Request 28    ===========
{'newest_id': '1518728817807929345', 'oldest_id': '1518728741761208321', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630fx0e9sg2uhriuqnysb1q5'}

Request 29    ===========
{'newest_id': '1518728740574048257', 'oldest_id': '1518728669774028800', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630fwsrxtf9eqtrfi40qjse5'}

Request 30    ===========
{'newest_id': '1518728669702799361', 'oldest_id': '1518728602447224833', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630fwslffkyfh4dd2dua3ce5'}

Request 31    ===========
{'newest_id': '1518728601843257344', 'oldest_id': '1518728535099150337', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630fwl05l1qzd9ncn7aippj1'}

Request 32    ===========
{'newest_id': '1518728534331740163', 'oldest_id': '1518728460432297985', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630fwdeuixr74i931ligic1p'}

Request 33    ===========
{'newest_id': '1518728459605868545', 'oldest_id': '1518728389322244096', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630fw5sipd0xox9ad393xvul'}

Request 34    ===========
{'newest_id': '1518728387900157952', 'oldest_id': '1518728312906039296', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630fw5kxfsnjiexxnybie071'}

Request 35    ===========
{'newest_id': '1518728311618383872', 'oldest_id': '1518728230152413184', 'result_count': 99, 'next_token': 'b26v89c19zqg8o3fpytoe630fvxyjxx2algdhcvixxoql'}

Request 36    ===========
{'newest_id': '1518728229107941377', 'oldest_id': '1518728148472504320', 'result_count': 99, 'next_token': 'b26v89c19zqg8o3fpytoe630fvqb531kc5ku73wzuo399'}

Request 37    ===========
{'newest_id': '1518728148388622336', 'oldest_id': '1518728057959460868', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630fvinouztml0jz8eyeoy2l'}

Request 38    ===========
{'newest_id': '1518728057925865474', 'oldest_id': '1518727979932733443', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630eetfritg4djsyd9bzfwxp'}

Request 39    ===========
{'newest_id': '1518727978246676482', 'oldest_id': '1518727904888299520', 'result_count': 98, 'next_token': 'b26v89c19zqg8o3fpytoe630eet86k1fuo4nggpu9rqm5'}

Request 40    ===========
{'newest_id': '1518727904879915010', 'oldest_id': '1518727815549665283', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630eelkqmr9lsm7g976vbhbx'}

Request 41    ===========
{'newest_id': '1518727815436259330', 'oldest_id': '1518727744829464576', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630eedzg6hyvofgf46gg0qkd'}

Request 42    ===========
{'newest_id': '1518727744825303040', 'oldest_id': '1518727653825601537', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630ee6bzycdymil93zyapksd'}

Request 43    ===========
{'newest_id': '1518727653703835649', 'oldest_id': '1518727581931081731', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630edyqpckp44b2knyaho6t9'}

Request 44    ===========
{'newest_id': '1518727581847203840', 'oldest_id': '1518727506186190848', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630edyi30ey5btlwdk21f6nx'}

Request 45    ===========
{'newest_id': '1518727505565597696', 'oldest_id': '1518727409058648064', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630edqtki71uqgvc0728px8d'}

Request 46    ===========
{'newest_id': '1518727408777633792', 'oldest_id': '1518727340871716864', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630edj9bq7p1g61v8kfsvxq5'}

Request 47    ===========
{'newest_id': '1518727340720861186', 'oldest_id': '1518727270390812673', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630edbo1f94cp1l94k70dapp'}

Request 48    ===========
{'newest_id': '1518727270294331393', 'oldest_id': '1518727194675392512', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630ed41ouf5c390883g9z98d'}

Request 49    ===========
{'newest_id': '1518727194633252867', 'oldest_id': '1518727112831770625', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630ed3t1g70oyfisae3lq9vh'}

Request 50    ===========
{'newest_id': '1518727112487755776', 'oldest_id': '1518727035450974213', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630ecw6opqt8q26u4nae97ct'}

Request 51    ===========
{'newest_id': '1518727035333623809', 'oldest_id': '1518726957025959939', 'result_count': 99, 'next_token': 'b26v89c19zqg8o3fpytoe630cw6yrdhcwbpaakf9jg96l'}

Request 52    ===========
{'newest_id': '1518726956782694400', 'oldest_id': '1518726877426290688', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630cvzce6spgzv4s7y35y3r1'}

Request 53    ===========
{'newest_id': '1518726877245894656', 'oldest_id': '1518726804457984000', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630cvz4tiz6tkzwbbp86nukd'}

Request 54    ===========
{'newest_id': '1518726803023704064', 'oldest_id': '1518726735436603394', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630cvrjjdlb74in2s13ov2wt'}

Request 55    ===========
{'newest_id': '1518726735105339392', 'oldest_id': '1518726653421277186', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630cvjx5vvursphfnjmk6gsd'}

Request 56    ===========
{'newest_id': '1518726652578213888', 'oldest_id': '1518726578615762944', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630cvcatghz97tvadr2kya9p'}

Request 57    ===========
{'newest_id': '1518726578552901633', 'oldest_id': '1518726514325561345', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630cvc4bj29xrxfwp5t214zh'}

Request 58    ===========
{'newest_id': '1518726514149584896', 'oldest_id': '1518726435351019523', 'result_count': 99, 'next_token': 'b26v89c19zqg8o3fpytoe630cv4hyhrf6c4b648anw2gt'}

Request 59    ===========
{'newest_id': '1518726434080145411', 'oldest_id': '1518726369781460994', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630cuwwosv82544l83btyqnx'}

Request 60    ===========
{'newest_id': '1518726368971874304', 'oldest_id': '1518726279020703744', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630cup98q13s7a3d3k7nft6l'}

Request 61    ===========
{'newest_id': '1518726278425231361', 'oldest_id': '1518726199261941773', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630cuhmvjaxf7eo9rsp4wjnh'}

Request 62    ===========
{'newest_id': '1518726198825787395', 'oldest_id': '1518726119058464775', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630cuhe8fxgiyyzfw000sdx9'}

Request 63    ===========
{'newest_id': '1518726117837840384', 'oldest_id': '1518726043452030979', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630cu9sx8cmbc0yuxrftivlp'}

Request 64    ===========
{'newest_id': '1518726043263188993', 'oldest_id': '1518725976129212416', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630bdkm2xhser57v6pjj9vgd'}

Request 65    ===========
{'newest_id': '1518725975571320835', 'oldest_id': '1518725902997278720', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630bdkei4dkl27o5zh911dod'}

Request 66    ===========
{'newest_id': '1518725902640685056', 'oldest_id': '1518725826757509121', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630bdcs5jfqxhrky91ehy0sd'}

Request 67    ===========
{'newest_id': '1518725825478152198', 'oldest_id': '1518725753738780674', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630bd56us6ezzx0ila2j9z0d'}

Request 68    ===========
{'newest_id': '1518725753088745472', 'oldest_id': '1518725675296952320', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630bcxkhw8l7xnhrcufdx1tp'}

Request 69    ===========
{'newest_id': '1518725674487349249', 'oldest_id': '1518725594242027523', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630bcpy4jzzftedltqq68a65'}

Request 70    ===========
{'newest_id': '1518725594061619201', 'oldest_id': '1518725529087750149', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630bcpql3vu596334hsn6oot'}

Request 71    ===========
{'newest_id': '1518725527523241985', 'oldest_id': '1518725453305028609', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630bci59wa7dwvso8fcia83h'}

Request 72    ===========
{'newest_id': '1518725450385690624', 'oldest_id': '1518725375467081728', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630bcaix0gzpmrifbouau5bx'}

Request 73    ===========
{'newest_id': '1518725374980591616', 'oldest_id': '1518725304428212224', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630bcabcnl6gi2pyeaz6mb99'}

Request 74    ===========
{'newest_id': '1518725304059002880', 'oldest_id': '1518725229568266241', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630bc2p086jspf2t2k2ezm9p'}

Request 75    ===========
{'newest_id': '1518725229052190720', 'oldest_id': '1518725155492708354', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630bbv3pbfln6joqpkoe4y9p'}

Request 76    ===========
{'newest_id': '1518725155438022656', 'oldest_id': '1518725083203784705', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630bbnieplknylzzf22if2pp'}

Request 77    ===========
{'newest_id': '1518725081920380928', 'oldest_id': '1518725016589942786', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe630bbnauynk2jwtmu2sdixdp'}

Request 78    ===========
{'newest_id': '1518725016069758976', 'oldest_id': '1518724947861901312', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe6309uy40czm7tooaclg7plz1'}

Request 79    ===========
{'newest_id': '1518724947161485314', 'oldest_id': '1518724871068520448', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe6309uqip55jsxxrikz8m1i7x'}

Request 80    ===========
{'newest_id': '1518724870045147136', 'oldest_id': '1518724802315497475', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe6309uqb539rn94cwmwzhriwt'}

Request 81    ===========
{'newest_id': '1518724802072260611', 'oldest_id': '1518724722648920066', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe6309uiorwkcv0iybf3pbhc3h'}

Request 82    ===========
{'newest_id': '1518724722648829952', 'oldest_id': '1518724651790344192', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe6309ub3hg9jiscfpta17pocd'}

Request 83    ===========
{'newest_id': '1518724651366731781', 'oldest_id': '1518724576909406212', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe6309u3h50vn54zxrh3ttw871'}

Request 84    ===========
{'newest_id': '1518724576313810947', 'oldest_id': '1518724503261614080', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe6309u39kcwr0xcsq7w3j27b1'}

Request 85    ===========
{'newest_id': '1518724502385004546', 'oldest_id': '1518724427848036357', 'result_count': 99, 'next_token': 'b26v89c19zqg8o3fpytoe6309tvn7s5327mtueb4g1z0d'}

Request 86    ===========
{'newest_id': '1518724426899984384', 'oldest_id': '1518724363671027716', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe6309to2zracwgb4r8vg3e8ot'}

Request 87    ===========
{'newest_id': '1518724363603873793', 'oldest_id': '1518724270393896963', 'result_count': 99, 'next_token': 'b26v89c19zqg8o3fpytoe6309tgfj84qzvrxdpw5m8ayl'}

Request 88    ===========
{'newest_id': '1518724268393177088', 'oldest_id': '1518724200575422465', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe6309tg7z0rcek6yjr7pomcn1'}

Request 89    ===========
{'newest_id': '1518724198792941570', 'oldest_id': '1518724131583373314', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe6309t8movdh3rmbkmqcquykd'}

Request 90    ===========
{'newest_id': '1518724128739667968', 'oldest_id': '1518724048292876288', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe6309t0z9uwhuxh5v4hncrx4t'}

Request 91    ===========
{'newest_id': '1518724048087400450', 'oldest_id': '1518723980663918595', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe6308cbtgryjkk7v6x4yha5x9'}

Request 92    ===========
{'newest_id': '1518723979938349056', 'oldest_id': '1518723912980320257', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe6308cblwvjn8w22x53gbrjp9'}

Request 93    ===========
{'newest_id': '1518723912963706885', 'oldest_id': '1518723845250633728', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe6308c40n0y3vqxurmg86uni5'}

Request 94    ===========
{'newest_id': '1518723845175185408', 'oldest_id': '1518723774153207814', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe6308bwfcklqmzdtgj1ehvxj1'}

Request 95    ===========
{'newest_id': '1518723773456863235', 'oldest_id': '1518723715814592516', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe6308bw8veq104niwqcyab33x'}

Request 96    ===========
{'newest_id': '1518723715307130880', 'oldest_id': '1518723646021259264', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe6308bonl9608cwy7yf6n4uwt'}

Request 97    ===========
{'newest_id': '1518723645304197120', 'oldest_id': '1518723570662359040', 'result_count': 99, 'next_token': 'b26v89c19zqg8o3fpytoe6308bh2a1mptn2cu8wsmsoe5'}

Request 98    ===========
{'newest_id': '1518723570079252492', 'oldest_id': '1518723500210634752', 'result_count': 99, 'next_token': 'b26v89c19zqg8o3fpytoe6308bgupu4osuwdf6nppx1fh'}

Request 99    ===========
{'newest_id': '1518723499988164608', 'oldest_id': '1518723432992628738', 'result_count': 100, 'next_token': 'b26v89c19zqg8o3fpytoe6308b99fud34hgyotlpb81h9'}

In [5]:
import pandas as pd
df = pd.DataFrame(
    {'id': ids, 
     'tweet_text': tweet_texts, 
     'created_at': created_times,
     'source': sources,
     'public_metrics':public_metrics,
     'language': languages
    })
df

,id,tweet_text,created_at,source,public_metrics,language
0,1518731013777670146,@thepacketrat Funny coincidence. at one point ...,2022-04-25 23:17:44+00:00,Twitter Web App,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",en
1,1518731013383409668,Funny how that “NOW” in this thread is actuall...,2022-04-25 23:17:44+00:00,Twitter for iPhone,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",en
2,1518731012272160769,@MYiKONICS Funny\n\nFLASHBACK TRACK LIST\n#iKO...,2022-04-25 23:17:44+00:00,Twitter for Android,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",en
3,1518731011974221824,These bitches are so damn funny https://t.co/5...,2022-04-25 23:17:44+00:00,Twitter for iPhone,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",en
4,1518731011626053638,RHOA tik tok soooo funny it make me want to wa...,2022-04-25 23:17:44+00:00,Twitter for iPhone,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",en
...,...,...,...,...,...,...
9984,1518723435223998465,@PAPPYKOJO You funny pass 😎😎,2022-04-25 22:47:38+00:00,Twitter for iPhone,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",en
9985,1518723434896785408,@timandfriends Too funny coming from someone t...,2022-04-25 22:47:38+00:00,Twitter Web App,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",en
9986,1518723434372493313,RT @raya17_salvador: Shrek In Spanish is funny...,2022-04-25 22:47:37+00:00,Twitter Web App,"{'retweet_count': 566, 'reply_count': 0, 'like...",en
9987,1518723433055588352,@VincentEternal8 @Spidey2307 Funny because he ...,2022-04-25 22:47:37+00:00,Twitter for Android,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",en
9988,1518723432992628738,RT @gloomfather: Lol that’s funny dude. Remind...,2022-04-25 22:47:37+00:00,Twitter for Android,"{'retweet_count': 5214, 'reply_count': 0, 'lik...",en

In [6]:
normalized_json = pd.json_normalize(df.public_metrics)
normalized_json

      retweet_count  reply_count  like_count  quote_count
0                 0            0           0            0
1                 0            0           0            0
2                 0            0           0            0
3                 0            0           0            0
4                 0            0           0            0
...             ...          ...         ...          ...
9984              0            0           0            0
9985              0            0           0            0
9986            566            0           0            0
9987              0            0           0            0
9988           5214            0           0            0

[9989 rows x 4 columns]

In [7]:
merged_df = pd.merge(df, normalized_json, left_index=True, right_index=True)
merged_df

,id,tweet_text,created_at,source,public_metrics,language,retweet_count,reply_count,like_count,quote_count
0,1518731013777670146,@thepacketrat Funny coincidence. at one point ...,2022-04-25 23:17:44+00:00,Twitter Web App,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",en,0,0,0,0
1,1518731013383409668,Funny how that “NOW” in this thread is actuall...,2022-04-25 23:17:44+00:00,Twitter for iPhone,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",en,0,0,0,0
2,1518731012272160769,@MYiKONICS Funny\n\nFLASHBACK TRACK LIST\n#iKO...,2022-04-25 23:17:44+00:00,Twitter for Android,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",en,0,0,0,0
3,1518731011974221824,These bitches are so damn funny https://t.co/5...,2022-04-25 23:17:44+00:00,Twitter for iPhone,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",en,0,0,0,0
4,1518731011626053638,RHOA tik tok soooo funny it make me want to wa...,2022-04-25 23:17:44+00:00,Twitter for iPhone,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",en,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
9984,1518723435223998465,@PAPPYKOJO You funny pass 😎😎,2022-04-25 22:47:38+00:00,Twitter for iPhone,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",en,0,0,0,0
9985,1518723434896785408,@timandfriends Too funny coming from someone t...,2022-04-25 22:47:38+00:00,Twitter Web App,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",en,0,0,0,0
9986,1518723434372493313,RT @raya17_salvador: Shrek In Spanish is funny...,2022-04-25 22:47:37+00:00,Twitter Web App,"{'retweet_count': 566, 'reply_count': 0, 'like...",en,566,0,0,0
9987,1518723433055588352,@VincentEternal8 @Spidey2307 Funny because he ...,2022-04-25 22:47:37+00:00,Twitter for Android,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",en,0,0,0,0
9988,1518723432992628738,RT @gloomfather: Lol that’s funny dude. Remind...,2022-04-25 22:47:37+00:00,Twitter for Android,"{'retweet_count': 5214, 'reply_count': 0, 'lik...",en,5214,0,0,0

In [8]:
merged_df.to_csv("TweetsOne.csv")